FROM python:3.9-slim-bullseye

WORKDIR /app

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY server.py .

COPY functions.py .

COPY bot_command.py .

COPY gpt.py .

CMD ["python3", "-u", "server.py"]