version: '3'

services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    environment:
      - DB_PASSW=ProgettoCyber2023!

      - DB_HOST=postgresql

      - DB_NAME=postgres

      - DB_USER=postgres

      - DB_PORT=5432

      - BOT_TOKEN=ZWNmYThlYTItODYyZi00OTNiLTkzN2YtNWJlMDEzODQwZGZkYzEyN2NjYWYtYjIy_PF84_9db17efa-dc2f-4ca3-90ae-30a52866391a

      - WEBEX_TOKEN=ZWNmYThlYTItODYyZi00OTNiLTkzN2YtNWJlMDEzODQwZGZkYzEyN2NjYWYtYjIy_PF84_9db17efa-dc2f-4ca3-90ae-30a52866391a

      - FLASK_RUN_PORT=3000
    ports:
      - 3000:3000/tcp
    depends_on:
      - postgresql
    restart: always

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - DB_PASSW=ProgettoCyber2023!

      - DB_HOST=postgresql

      - DB_NAME=postgres

      - DB_USER=postgres

      - DB_PORT=5432

      - BOT_TOKEN=ZWNmYThlYTItODYyZi00OTNiLTkzN2YtNWJlMDEzODQwZGZkYzEyN2NjYWYtYjIy_PF84_9db17efa-dc2f-4ca3-90ae-30a52866391a

      - OPENAI_TOKEN=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

      - WEBEX_TOKEN=ZWNmYThlYTItODYyZi00OTNiLTkzN2YtNWJlMDEzODQwZGZkYzEyN2NjYWYtYjIy_PF84_9db17efa-dc2f-4ca3-90ae-30a52866391a

      - UMBRELLA_AUTH=MWYyMzZjMjFhOTg1NGE2ZmFjODBlYWE3OTNkZjAzMzc6NGJlMGE3NDBjZTkzNGIxNmE5YjU0MzIzOWQ1ZTY3OWI=
                      
    depends_on:
      - postgresql
    restart: always
  
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=ProgettoCyber2023!
    volumes: 
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
 