version: '3'

services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    environment:
      - DB_PASSW=ProgettoCyber2023!
      - DB_HOST=postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PORT=5432
      - BOT_TOKEN=ZTQ1OWQyYTMtOGExYS00MGY0LWI2NzYtMTM0NWEwMDg1NGE3NTcyMTEzMzYtMTJi_PE93_028ef8d7-2681-410e-94a1-aba330df7a76
      - WEBEX_TOKEN=ZTQ1OWQyYTMtOGExYS00MGY0LWI2NzYtMTM0NWEwMDg1NGE3NTcyMTEzMzYtMTJi_PE93_028ef8d7-2681-410e-94a1-aba330df7a76
      - FLASK_RUN_PORT=3000
    ports:
      - 3000:3000/tcp
    depends_on:
      - postgresql
    restart: always

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - DB_PASSW=ProgettoCyber2023!
      - DB_HOST=postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PORT=5432
      - BOT_TOKEN=ZTQ1OWQyYTMtOGExYS00MGY0LWI2NzYtMTM0NWEwMDg1NGE3NTcyMTEzMzYtMTJi_PE93_028ef8d7-2681-410e-94a1-aba330df7a76
      - OPENAI_TOKEN=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
      - WEBEX_TOKEN=ZTQ1OWQyYTMtOGExYS00MGY0LWI2NzYtMTM0NWEwMDg1NGE3NTcyMTEzMzYtMTJi_PE93_028ef8d7-2681-410e-94a1-aba330df7a76
      - UMBRELLA_AUTH=MWYyMzZjMjFhOTg1NGE2ZmFjODBlYWE3OTNkZjAzMzc6NGJlMGE3NDBjZTkzNGIxNmE5YjU0MzIzOWQ1ZTY3OWI=
                      
    depends_on:
      - postgresql
    restart: always
  
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=ProgettoCyber2023!
    volumes: 
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
 